version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npx tailwindcss init
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./dist $S3_BUCKET