version: 0.2

phases:
  install:
    commands:
      - echo trying
      - echo $S3_BUCKET
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync --debug ./dist $S3_BUCKET